services:
  frontend:
    image: myfrontend
    build:
      context: .
      dockerfile: Dockerfile
    container_name: myfrontend
    ports:
      - 80:80
    networks:
      - mynetwork

networks:
  mynetwork: